name: Merge and Append
on:
  pull_request:
    types: [opened, synchronize]
env:
  MAIN_BRANCH: main
  SUBMODULE_BRANCH: submodule
  ALIAS_FILE_PATH: submodule/alias.txt
  README_FILE_PATH: README.md
jobs:
  merge-and-append:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge pull request
        uses: rtCamp/github-action-auto-merge@v1.2.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: "auto-merge"

      - name: Append alias.txt to README.md
        uses: actions/checkout@v2
        with:
          ref: ${{ env.MAIN_BRANCH }}
          path: main-branch

      - name: Read alias.txt
        id: read-alias
        run: |
          echo "::set-output name=contents::$(cat $ALIAS_FILE_PATH)"

      - name: Append contents to README.md
        run: |
          echo "$(cat main-branch/$README_FILE_PATH)$(echo)$(echo)::set-output name=contents::${{ steps.read-alias.outputs.contents }}" > main-branch/$README_FILE_PATH

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automatically append alias.txt to README.md"
          commit_options: "--no-verify"
