name: Merge Request

on:
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Read Alias File
        id: read_alias
        run: |
          cd submodule
          cat alias.txt
      - name: Accept Merge Request
        uses: github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const payload = context.payload;
            const pullRequest = payload.pull_request;
            const owner = payload.repository.owner.login;
            const repo = payload.repository.name;
            await github.pulls.merge({
              owner,
              repo,
              pull_number: pullRequest.number,
              merge_method: 'merge',
            });
      - name: Append to README
        uses: actions/github-script@v4
        with:
          script: |
            const payload = context.payload;
            const pullRequest = payload.pull_request;
            const owner = payload.repository.owner.login;
            const repo = payload.repository.name;
            const aliasFile = await github.request(`GET /repos/${owner}/${repo}/contents/submodule/alias.txt`);
            const aliasContent = Buffer.from(aliasFile.data.content, 'base64').toString('utf-8');
            const readmeFile = await github.request(`GET /repos/${owner}/${repo}/contents/README.md`);
            const readmeContent = Buffer.from(readmeFile.data.content, 'base64').toString('utf-8');
            const updatedContent = readmeContent + '\n' + aliasContent;
            await github.repos.createOrUpdateFileContents({
              owner,
              repo,
              path: 'README.md',
              message: `Updated README with ${aliasFile.name}`,
              content: Buffer.from(updatedContent).toString('base64'),
              sha: readmeFile.data.sha,
              branch: 'main',
            });
